---
title: My Jira Dashboard
refreshInterval: 60s
grid:
  columns: 2
  rows: 5

customization:
  grid:
    gap: 1rem
    padding: 0rem
    marginTop: 0rem
  card:
    borderColor: "#ddd"
    padding: 1rem
    backgroundColor: "#fff"
    borderRadius: 0.5rem
    boxShadow: 0 2px 4px rgba(0, 0, 0, 0.05)
  header:
    align: center
    marginBottom: 0.5rem
  footer:
    marginTop: 1rem
  font:
    family: "Segoe UI, sans-serif"
    size: 16px

providers:
  jira-v3:
    baseURL: "http://localhost:8081"
    skipTLSVerify: true
    auth:
      basic:
        username: "me@example.com"
        password: "JIRA_API_TOKEN"
  jira-v2:
    baseURL: "http://localhost:8081"

tiles:
  - title: Prod Alert
    template: env_alert.gohtml
    position:
      row: 1
      col: 1
      colSpan: 2
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/search
      ttl: 20s
      query:
        jql: filter=17203
  - title: Engineer of the Week
    template: eotw.gohtml
    position:
      row: 2
      col: 1
      colSpan: 2
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/issue/ENV-64
      ttl: 60s
      query:
        fields: assignee,summary,status
  - title: Env Epics
    template: epics.gohtml
    position:
      row: 3
      col: 1
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/search
      ttl: 20s
      query:
        jql: filter=17201
  - title: Open Environment Issues
    template: issues.gohtml
    position: { row: 3, col: 2 }
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/search
      ttl: 20s
      query:
        jql: filter=17203
  - title: Two Dimensional Open Environment Issues
    template: env_issues.gohtml
    position: { row: 4, col: 1 }
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/search
      ttl: 20s
      query:
        jql: filter=17203
  - title: Top 3 most Issues
    template: podium.gohtml
    position: { row: 4, col: 2 }
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/search
      ttl: 20s
      query:
        jql: filter=17203
  - title: "Issue Statistics: Open Environment Issues (Assignee)"
    template: assignees.gohtml
    position: { row: 5, col: 1, colSpan: 2 }
    request:
      provider: jira-v2
      method: GET
      path: /rest/api/2/search
      ttl: 20s
      query:
        jql: filter=17203
