---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kubernetes/
configMapGenerator:
  - name: tiledash-config
    files:
      - config.yaml
  - name: tiledash-templates
    files:
      - templates/assignees.gohtml
      - templates/env_alert.gohtml
      - templates/env_issues.gohtml
      - templates/eotw.gohtml
      - templates/epics.gohtml
      - templates/functions.gohtml
      - templates/issues.gohtml
      - templates/motd.gohtml
      - templates/podium.gohtml
